FROM python:3.10-slim

WORKDIR /python-docker

# COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install git -y
RUN touch requirements.txt
RUN echo flask >> requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install "git+https://github.com/openai/whisper.git" 
RUN apt-get install -y ffmpeg

COPY ./whisper-ai .

EXPOSE 5000

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]