name: melvin-test
services:
  backend:
    restart: unless-stopped
    image: ghcr.io/shuffle-project/melvin-backend:${BACKEND_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      asr:
        condition: service_healthy
    ports:
      - 127.0.0.1:3000:3000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:3000 || exit 1
      interval: 5s
      retries: 10
      timeout: 3s
    volumes:
      - ./backend.config.yml:/app/config.yml
      - ${DATA_ROOT_PATH}/backend/media:/app/media/projects

  mongodb:
    image: mongo:7
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_PATH}/mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/captioning --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_PATH}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  frontend:
    image: ghcr.io/shuffle-project/melvin-frontend:${FRONTEND_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 127.0.0.1:8080:80
    environment:
      - FRONTEND_BASE_URL=http://localhost:8080 # TODO: replace with your frontend URL
      - BACKEND_BASE_URL=https://localhost:3000 # TODO: replace with your backend URL
      - MELVIN_DISABLE_LANDING_PAGE=false # TODO: set to true if you want to disable the landing page
      - MELVIN_DISABLE_TUTORIAL_VIDEOS=false # TODO: set to true if you want to disable the tutorial videos
      - MELVIN_IMPRINT_URL= # TODO: your default imprint URL
      - MELVIN_PRIVACY_URL= # TODO: your default privacy URL
      - MELVIN_ACCESSIBILITY_STATEMENT_URL= # TODO: your default accessibility statement URL
      - MELVIN_DE_IMPRINT_URL= # TODO: optional, if you have a German imprint URL
      - MELVIN_DE_PRIVACY_URL= # TODO: optional, if you have a German privacy URL
      - MELVIN_DE_ACCESSIBILITY_STATEMENT_URL= # TODO: optional, if you have a German accessibility statement URL
      - MELVIN_EN_IMPRINT_URL= # TODO: optional, if you have a English imprint URL
      - MELVIN_EN_PRIVACY_URL= # TODO: optional, if you have a English privacy URL
      - MELVIN_EN_ACCESSIBILITY_STATEMENT_URL= # TODO: optional, if you have a English accessibility statement URL
      # if no language specific imprint or privacy URL is set, the default URLs will be used

  asr:
    image: ghcr.io/shuffle-project/melvin-asr:${ASR_API_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-asr
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT_PATH}/asr:/melvin-asr/data
      - ${WHISPER_MODELS_CACHE_PATH}:/melvin-asr/data/models
      - ./asr.config.yml:/melvin-asr/config.yml
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: curl --fail -X GET http://localhost:8000/health || exit 1
      interval: 10s
      retries: 10
      timeout: 3s
    # Enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ["0"]
    #           capabilities: [gpu]
