

# Auth / Login
###
POST http://localhost:3000/auth/login 
content-type: application/json

{
    "email":"jane.doe@example.com",
    "password":"secret"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "token":"token"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"test@test.de",
    "password":"password",
    "name":"tester1"
}
###
POST http://localhost:3000/auth/verify-email
###
POST http://localhost:3000/auth/guest { inviteLink }