export const TITLES = [
  'Grundlagen der Barrierefreiheit',
  'Testvideo',
  'Projekt',
  'Webdesign für Anfänger*innen',
  'Web-Entwicklung für Fortgeschrittene',
  'Datenbanken',
  'Adv. Game Dev.',
  'Agiles Proj. Mgmt.',
  'Digitale Barrierefreiheit',
  'Entw.v.Rich Media Syst',
  'Erstsemesterbegrüßung',
  'Informationsveranstaltung',
  'Interakt. Medien',
  'Künstl.Intell.i.d.Int',
  'Mgmt. v. IT-Projekten',
  'Requirem. Analysis',
  'Transmed. Exp. Design',
  'Vollversammlung',
];
export const CAPTION_TEXTS = [
  'Herzlich Willkommen zur Vorlesung Human Computer Interaction im Wintersemester 2021 2022.',
  'Mein Name ist Gottfried Zimmermann und ich bin seit 2011 an der Hochschule der Medien tätig.',
  'Entschuldigen Sie, ich habe eine Frage, und zwar kann ich die Folien von heute online nicht finden, haben Sie die schon hochgeladen?',
  'Ja, nochmal für alle: Falls Sie die Folien parallel auf ihrem Computer öffnen möchten, finden Sie sie im Ilias Kurs.',
  'Herzlich willkommen zum Vortrag "Barrierefreiheit, die allen nützt - Innovative Maßnahmen in der Hochschullehre im Sinne von Universal Design for Learning".',
  'Ich bin Gottfried Zimmermann, Professor an der Hochschule der Medien in Stuttgart und bin der fachliche Leiter des',
  'Kompetenzzentrums für digitale Barrierefreiheit und auch Leiter des Forschungsprojekts SHUFFLE.',
  'In der Hochschullehre haben wir alle zumindest seit Corona irgendwie Erfahrungen mit digital',
  'unterstützter Lehre gemacht und es ist auch jetzt schon klar nach Corona ist nichts,',
  'wird nicht wieder so sein wie vor Corona.',
  'Es werden manche der Dinge, die wir durchgeführt haben, bleiben und es wird mehr digital übermittelte Lehre geben als vorher.',
  'Und die Frage dabei ist, welche Rolle wird Barrierefreiheit dabei spielen?',
  'Wird Barrierefreiheit eine hochrangige Stellung Priorität eingeräumt werden?',
  'Oder wird es halt stiefmütterlich behandelt werden, wie oftmals zurzeit, als man schnell irgendwelche Maßnahmen ergreifen musste?',
  'Wenn wir es schaffen, dass die Maßnahmen der Barrierefreiheit allen Studierenden zugutekommen, nicht nur denen,',
  'sage ich mal den relativ kleinen Teil der Studierenden, die jetzt irgendwo registriert sind oder offensichtlich eine Behinderung haben.',
  'Wenn es das gelingt, dass wir sozusagen die gesamte Studierendenschaft im Blick haben, dann wird es auch leichter werden,',
  'diese Maßnahme durchzusetzen und die Lehrenden und auch die des Management der Hochschulen dafür zu gewinnen.',
  'Und das ist die Frage Wie können wir das machen?',
  'Ich behelfe mich in dieser Argumentation dem Framework Universal Design von Löning, auch abgekürzt UvdL.',
  'Das wird noch häufiger in diesem Vortrag vorkommen. Es ist ein Framework für Lehre und Lernen,',
  'wurde von den Kast Gründern eine Mail von mir und David Rose in den 90er Jahren gegründet',
  'und auch erklärt wurde es von vielen Lehrenden an Schulen und Hochschulen aufgenommen,',
  'zum Teil im Zusammenhang mit Barrierefreiheit, zum Teil auch ganz allgemein.',
  'Law verfolgt einen konzentrierten Ansatz im  egensatz zu einem lehrenden zentrierten Ansatz.',
  'Es geht darum, die Lernenden zu motivieren, sich mit einem Thema zu beschäftigen,',
  'und zwar auf verschiedene Weise durch Wahlmöglichkeiten, durch eine echte intrinsische Motivation, durch echtes Interesse fördern.',
  'Es geht darum, Lerninhalte auf verschiedene Weise darzustellen. Auch Alternative weisen durch Text, Bilder, Videos.',
  'Im Englischen nennt sich das Representation. Und es geht auch darum, drittens Lernende zu aktivieren, Interesse zu wecken,',
  'Motivation bzw. eigenständig dazu zu bringen, sich mit dem Thema Hands on zu befassen.',
  'Wenn Sie dann aktiver Expression und auch verschiedene Formen zu erlauben.',
  'Zum Beispiel, wie man Prüfungen abnimmt, sei es nur mündlich oder schriftlich oder andere Formen.',
  'Das ist ein Poster, das die neuen Guidelines für Universal Design Learning zusammenfasst, und zwar auf drei Säulen.',
  'Ich fange in der Mitte mit der mittleren Säule an Problematik und means of representation.',
  'Da geht es um das. Also um das Was des Lernens, also das Vermitteln von Lerninhalten über.',
  'Und jetzt kommen auch diese drei Kriterien über verschiedenartige Wahrnehmungs Möglichkeiten,',
  'also dass man es als Text, Bild, Diagramm, Video, Audio vermittelt,',
  'dann auch an verschiedene Optionen für Sprache und Symbole vermitteln, dass man erklärt,',
  'wenn Symbole nicht eindeutig sind oder auch mathematische Formeln Notationen erklärt, dass man auch mehrere Sprachen fördert.',
  'Und da gehört auch dazu das Verständnis, dass man verschiedene Möglichkeiten bietet, die das Hintergrundwissen sich anzueignen,',
  'zu verlinken auf Hintergrundwissen, wenn das fehlt und generell Beziehungen zwischen zwei Einheiten deutlich macht.',
];

// https://www.andiamo.co.uk/resources/iso-language-codes/
export const LANGUAGES = ['de-DE', 'de-DE', 'en-US', 'en-GB', 'fr-FR', 'es-ES'];
