version: '3'

volumes:
  audio_files:
  settings:
  transcripts:

services:
  mongodb:
    image: mongo:5
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    ports:
      - 6379:6379
  kurento:
    container_name: ${COMPOSE_PROJECT_NAME}-kurento
    image: kurento/kurento-media-server
    ports:
      - 8888:8888/tcp
      - 5000-5050:5000-5050/udp
    restart: unless-stopped
    volumes:
      - ../media/kurento/:/var/lib/kurento/:rw
    environment:
      - -GST_DEBUG="Kurento*:5"

  api:
    image: ghcr.io/shuffle-project/asr-api-api:deploy
    container_name: ${COMPOSE_PROJECT_NAME}-asr-api-api
    volumes:
      - audio_files:/data/audio_files
      - settings:/data/settings
      - transcripts:/data/transcripts
    ports:
      - '8041:8041'

  whispercpp_runner:
    image: ghcr.io/shuffle-project/asr-api-whispercpp_runner:deploy
    container_name: ${COMPOSE_PROJECT_NAME}-asr-api-whispercpp_runner
    volumes:
      - audio_files:/data/audio_files
      - settings:/data/settings
      - transcripts:/data/transcripts
    depends_on:
      - api

  # whisper:
  #   container_name: ${COMPOSE_PROJECT_NAME}-whisper
  #   build:
  #     dockerfile: ../Dockerfile.whisper
  #   ports:
  #     - 5000:5000

  # libretranslate:
  #   image: libretranslate/libretranslate
  #   container_name: ${COMPOSE_PROJECT_NAME}-libretranslate
  #   restart: unless-stopped
